controllers/autorController.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from models.autorModel import AutorModel

autorbp = Blueprint("autor", __name__)

@autorbp.route("/autor/crear", methods = ['GET','POST'])
def crear():
    if request.method == 'POST':
        nombre_autor = request.form['nombre_autor']

        retorno = AutorModel().crearAutor(nombre_autor)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('autor.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo crear el autor", "error"))
            return render_template("/autor/crear.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/autor/crear.html")

@autorbp.route("/autor/", methods=['GET', 'POST'])
def index():
    autores = AutorModel().listarAutores()
    return render_template('/autor/index.html',autores = autores)

@autorbp.route("/autor/editar/<int:id>", methods = ['GET','POST'])
def editar(id):
    autor = AutorModel().buscarAutor(id)
    if request.method == 'POST':
        nombre_autor = request.form['nombre_autor']

        retorno = AutorModel().actualizarAutor(id, nombre_autor)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('autor.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo editar el autor", "error"))
            return render_template("/autor/editar.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/autor/editar.html", autor = autor)

@autorbp.route("/autor/detalle/<int:id>")
def detalle(id):
    autor = AutorModel().buscarAutor(id)
    return render_template('/autor/detalle.html',autor = autor)

@autorbp.route('/autor/eliminar/<int:id>', methods=['GET','POST'])
def eliminar(id):
    autor = AutorModel().buscarAutor(id)
    if request.method == 'POST':
        retorno = AutorModel().eliminarAutor(id)

        if retorno > 0:
            flash(("No se pudo eliminar el autor", "error"))
            return redirect(url_for('autor.index'))
        else:
            flash(("No se pudo eliminar el autor", "error"))
            return render_template("/autor/eliminar.html", autor = autor)
    return render_template("/autor/eliminar.html", autor = autor)
    

templates/autor/crear.html
{% extends 'layout_interno.html' %}

{% block title%} Crear Autor {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Crear Autor</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <div class="form-group">
                                <label for="nombre_autor">Nombre Autor</label>
                                <input name = "nombre_autor" id = "nombre_autor" type="text" class="form-control">
                            </div>
                            <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('autor.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/autor/detalle.html
{% extends 'layout_interno.html' %}

{% block title%} Detalle Autores {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Detalle Autor</h1>
                    </div>
                    <div class="card-body">
                        <ul>
                            <p><strong>ID: </strong>{{autor.id}}</p>
                            <p><strong>Nombre: </strong>{{autor.nombre_autor}}</p>
                            <a href="{{url_for('autor.index')}}" class="btn btn-success w-100 my-3">Volver</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/autor/editar.html
{% extends 'layout_interno.html' %}

{% block title%} Editar Autores {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Editar Autor</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{autor.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_autor">Nombre Autor</label>
                                <input name = "nombre_autor" id = "nombre_autor" type="text" class="form-control" value="{{autor.nombre_autor}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('autor.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/autor/eliminar.html
{% extends 'layout_interno.html' %}

{% block title%} Editar Autores {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Eliminar Autor</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{autor.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_autor">Nombre Autor</label>
                                <input disabled name = "nombre_autor" id = "nombre_autor" type="text" class="form-control" value="{{autor.nombre_autor}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Eliminar">
                                <a href="{{url_for('autor.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/autor/index.html
{% extends 'layout_interno.html' %}

{% block title%} Autores {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="offset-10 col-3 my-3">
                <a href="{{url_for('autor.crear')}}" class="btn btn-success">Crear Autor</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="card border border-dark shadow mb-3">
                <div class="card-header bg-primary">
                    <h1 class="h1 text-white text-center">Listado de  Autores</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="Tabla">
                            <thead class="table-primary">
                                <tr>
                                    <td>#</td>
                                    <td>Nombre</td>
                                    <td>Acciones</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for autor in autores %}
                                    <tr>
                                        <td>{{autor.id}}</td>
                                        <td>{{autor.nombre_autor}}</td>
                                        <td>
                                            <a href="{{url_for('autor.detalle', id=autor.id)}}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                                            <a href="{{url_for('autor.editar',id=autor.id)}}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                            <a href="{{url_for('autor.eliminar',id=autor.id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}