controllers/categoriaController.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from models.categoriaModel import CategoriaModel

categoriabp = Blueprint("categoria", __name__)

@categoriabp.route("/categoria/crear", methods = ['GET','POST'])
def crear():
    if request.method == 'POST':
        nombre_categoria = request.form['nombre_categoria']

        retorno = CategoriaModel().crearCategoria(nombre_categoria)
        print(retorno)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('categoria.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo crear el categoria", "error"))
            return render_template("/categoria/crear.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/categoria/crear.html")

@categoriabp.route("/categoria/", methods=['GET', 'POST'])
def index():
    categorias = CategoriaModel().listarCategorias()
    return render_template('/categoria/index.html',categorias = categorias)

@categoriabp.route("/categoria/editar/<int:id>", methods = ['GET','POST'])
def editar(id):
    categoria = CategoriaModel().buscarCategoria(id)
    if request.method == 'POST':
        nombre_categoria = request.form['nombre_categoria']

        retorno = CategoriaModel().actualizarCategoria(id, nombre_categoria)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('categoria.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo editar el categoria", "error"))
            return render_template("/categoria/editar.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/categoria/editar.html", categoria = categoria)

@categoriabp.route("/categoria/detalle/<int:id>")
def detalle(id):
    categoria = CategoriaModel().buscarCategoria(id)
    return render_template('/categoria/detalle.html',categoria = categoria)

@categoriabp.route('/categoria/eliminar/<int:id>', methods=['GET','POST'])
def eliminar(id):
    categoria = CategoriaModel().buscarCategoria(id)
    if request.method == 'POST':
        retorno = CategoriaModel().eliminarCategoria(id)

        if retorno > 0:
            flash(("No se pudo eliminar el categoria", "error"))
            return redirect(url_for('categoria.index'))
        else:
            flash(("No se pudo eliminar el categoria", "error"))
            return render_template("/categoria/eliminar.html", categoria = categoria)
    return render_template("/categoria/eliminar.html", categoria = categoria)
    

templates/categoria/crear.html
{% extends 'layout_interno.html' %}

{% block title%} Crear Categoria {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Crear Categoria</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <div class="form-group">
                                <label for="nombre_categoria">Nombre Categoria</label>
                                <input name = "nombre_categoria" id = "nombre_categoria" type="text" class="form-control">
                            </div>
                            <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('categoria.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/categoria/detalle.html
{% extends 'layout_interno.html' %}

{% block title%} Detalle Categoria {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Detalle Categoria</h1>
                    </div>
                    <div class="card-body">
                        <ul>
                            <p><strong>ID: </strong>{{categoria.id}}</p>
                            <p><strong>Nombre: </strong>{{categoria.nombre_categoria}}</p>
                            <a href="{{url_for('categoria.index')}}" class="btn btn-success w-100 my-3">Volver</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/categoria/editar.html
{% extends 'layout_interno.html' %}

{% block title%} Editar Categoria {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Editar Autor</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{categoria.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_categoria">Nombre Autor</label>
                                <input name = "nombre_categoria" id = "nombre_categoria" type="text" class="form-control" value="{{categoria.nombre_categoria}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('categoria.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/categoria/eliminar.html
{% extends 'layout_interno.html' %}

{% block title%} Eliminar Categoría {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Eliminar Categoria</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{categoria.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_categoria">Nombre Categoria</label>
                                <input disabled name = "nombre_categoria" id = "nombre_categoria" type="text" class="form-control" value="{{categoria.nombre_categoria}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Eliminar">
                                <a href="{{url_for('categoria.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/categoria/index.html
{% extends 'layout_interno.html' %}

{% block title%} Categorias {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="offset-10 col-3 my-3">
                <a href="{{url_for('categoria.crear')}}" class="btn btn-success">Crear Categoría</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="card border border-dark shadow mb-3">
                <div class="card-header bg-primary">
                    <h1 class="h1 text-white text-center">Listado de  Categorias</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="Tabla">
                            <thead class="table-primary">
                                <tr>
                                    <td>#</td>
                                    <td>Nombre</td>
                                    <td>Acciones</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for categoria in categorias %}
                                    <tr>
                                        <td>{{categoria.id}}</td>
                                        <td>{{categoria.nombre_categoria}}</td>
                                        <td>
                                            <a href="{{url_for('categoria.detalle', id=categoria.id)}}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                                            <a href="{{url_for('categoria.editar',id=categoria.id)}}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                            <a href="{{url_for('categoria.eliminar',id=categoria.id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}