controllers/libroController.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from models.libroModel import LibroModel
from models.autorModel import AutorModel
from models.editorialModel import EditorialModel
from models.categoriaModel import CategoriaModel
from werkzeug.utils import secure_filename
import os
import uuid


FOLDER_IMG = 'static/img'


librobp = Blueprint("libro", __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@librobp.route("/libro", methods=['GET', 'POST'])
@librobp.route("/libro/", methods=['GET', 'POST'])
def index():
    libros = LibroModel().listarLibros()
    return render_template('/libro/index.html', libros = libros)


@librobp.route("/libro/crear", methods = ['GET','POST'])
def crear():
    autores = AutorModel().listarAutores()
    editoriales = EditorialModel().listarEditoriales()
    categorias = CategoriaModel().listarCategorias()
    if request.method == 'POST':
        precio = request.form['precio']
        nombre_libro = request.form['nombre_libro']
        cantidad = request.form['cantidad']
        autor = request.form['autor']
        editorial = request.form['editorial']
        categoria = request.form['categoria']
        imagen = request.files['url_imagen']
        url_imagen = None

        if imagen and  allowed_file(imagen.filename):
            filename = secure_filename(imagen.filename)
            unique_filename = str(uuid.uuid4()) + "_" + filename
            url_imagen = f"img/{unique_filename}"
            imagen.save(os.path.join(FOLDER_IMG, unique_filename))


        retorno = LibroModel().crearLibro(precio, nombre_libro, cantidad, autor, editorial, categoria, url_imagen)
        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('libro.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo crear el libro", "error"))
            return render_template("/libro/crear.html",
                                    autores = autores,
                                    editoriales = editoriales,
                                    categorias = categorias)

    # Si es GET, solo mostramos el formulario
    return render_template("/libro/crear.html",
                           autores = autores,
                           editoriales = editoriales,
                           categorias = categorias
                           )

@librobp.route("/libro/detalle/<int:id>")
def detalle(id):
    libro = LibroModel().buscarLibro(id)
    return render_template('/libro/detalle.html',libro = libro)

@librobp.route('/libro/eliminar/<int:id>', methods=['GET','POST'])
def eliminar(id):
    libro = LibroModel().buscarLibro(id)
    if request.method == 'POST':
        retorno = LibroModel().eliminarLibro(id)

        if retorno > 0:
            flash(("No se pudo eliminar el libro", "error"))
            return redirect(url_for('libro.index'))
        else:
            flash(("No se pudo eliminar el libro", "error"))
            return render_template("/libro/eliminar.html", libro = libro)
    return render_template("/libro/eliminar.html", libro = libro)


@librobp.route("/libro/editar/<int:id>", methods = ['GET','POST'])
def editar(id):
    libro = LibroModel().buscarLibro(id)
    autores = AutorModel().listarAutores()
    editoriales = EditorialModel().listarEditoriales()
    categorias = CategoriaModel().listarCategorias()
    if request.method == 'POST':
        precio = request.form['precio']
        nombre_libro = request.form['nombre_libro']
        cantidad = request.form['cantidad']
        autor = request.form['autor']
        editorial = request.form['editorial']
        categoria = request.form['categoria']
        url_imagen = None
        imagen = request.files['url_imagen']
        if imagen and allowed_file(imagen.filename):
            unique_filename = secure_filename(imagen.filename)
            url_imagen = f"img/{unique_filename}"
            imagen.save(os.path.join(FOLDER_IMG, unique_filename))
        retorno = LibroModel().actualizarLibro(id,  precio, cantidad, nombre_libro, autor, editorial, categoria, url_imagen)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('libro.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo editar el libro", "error"))
            return render_template("/libro/editar.html",
                                   autores = autores,
                                   editoriales = editoriales,
                                   categorias = categorias,
                                   libro = libro)

    # Si es GET, solo mostramos el formulario
    return render_template("/libro/editar.html", 
                           libro = libro,
                           autores = autores,
                           editoriales = editoriales,
                           categorias = categorias)

templates/libro/crear.html
{% extends 'layout_interno.html' %}

{% block title%} Crear Libro {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Crear Libro</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Libro</label>
                                <input  name = "nombre_libro" id = "nombre_libro" type="text" class="form-control" >
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Categoria</label>
                                <select class= "form-control" name="categoria" id="categoria">
                                    <option value="">Seleccione una opción</option>
                                    {% for categoria in categorias %}
                                        <option value="{{categoria.id}}" >{{categoria.nombre_categoria}}</option>
                                    {% endfor %}
                                </select>     
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Autor</label>
                                <select class= "form-control" name="autor" id="autor">
                                    <option value="">Seleccione una opción</option>
                                    {% for autor in autores %}
                                        <option value="{{autor.id}}">{{autor.nombre_autor}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Editorial</label>
                                <select class= "form-control" name="editorial" id="editorial">
                                    <option value="">Seleccione una opción</option>
                                    {% for editorial in editoriales %}
                                        <option value="{{editorial.id}}">{{editorial.nombre_editorial}}</option>
                                    {% endfor %}
                                </select>       
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Precio</label>
                                <input name = "precio" id = "precio" type="text" class="form-control" >
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Cantidad</label>
                                <input  name = "cantidad" id = "cantidad" type="text" class="form-control" value=>
                            </div>
                            <div class="form-group">
                                <label for="url_imagen">Imagen</label>
                                <input class= "form-control" type="file" name="url_imagen" id="url_imagen">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('libro.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/libro/detalle.html
{% extends 'layout_interno.html' %}

{% block title%} Detalle Libro {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Detalle Libro</h1>
                    </div>
                    <div class="card-body">
                        <ul>
                            <p><strong>ID: </strong>{{libro.id}}</p>
                            <p><strong>Nombre: </strong>{{libro.nombre_libro}}</p>
                            <p><strong>Categoría: </strong>{{libro.nombre_categoria}}</p>
                            <p><strong>Editorial: </strong>{{libro.nombre_editorial}}</p>
                            <p><strong>Autor: </strong>{{libro.nombre_autor}}</p>
                            <p><strong>Precio: </strong>{{libro.precio}}</p>
                            <p><strong>Cantidad: </strong>{{libro.cantidad}}</p>
                            <p><strong>Activo: </strong>{{ "Activo" if libro.activo else "Inactivo" }}</p>
                            <a href="{{url_for('libro.index')}}" class="btn btn-success w-100 my-3">Volver</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/libro/editar.html
{% extends 'layout_interno.html' %}

{% block title%} Editar Libro {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Editar Libro</h1>
                    </div>
                    <div class="card-body">
                        <form enctype="multipart/form-data" action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type="hidden" name="{{libro.id}}" id="{{libro.id}}" value="{{libro.id}}">
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Libro</label>
                                <input  name = "nombre_libro" id = "nombre_libro" type="text" class="form-control" value="{{libro.nombre_libro}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Categoria</label>
                                <select class= "form-control" name="categoria" id="categoria">
                                    <option value="">Seleccione una opción</option>
                                    {% for categoria in categorias %}
                                        {% if categoria.id == libro.id_categoria %}
                                            <option value="{{categoria.id}}" selected>{{categoria.nombre_categoria}}</option>
                                        {% else %}
                                            <option value="{{categoria.id}}">{{categoria.nombre_categoria}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>     
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Autor</label>
                                <select class= "form-control" name="autor" id="autor">
                                    <option value="">Seleccione una opción</option>
                                    {% for autor in autores %}
                                        {% if autor.id == libro.id_autor %}
                                            <option value="{{autor.id}}" selected>{{autor.nombre_autor}}</option>
                                        {% else %}
                                            <option value="{{autor.id}}">{{autor.nombre_autor}}</option>
                                        {% endif %}
                                        
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Editorial</label>
                                <select class= "form-control" name="editorial" id="editorial">
                                    <option value="">Seleccione una opción</option>
                                    {% for editorial in editoriales %}
                                        {% if editorial.id == libro.id_editorial %}
                                            <option value="{{editorial.id}}" selected>{{editorial.nombre_editorial}}</option>
                                        {% else %}
                                            <option value="{{editorial.id}}">{{editorial.nombre_editorial}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>       
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Precio</label>
                                <input name = "precio" id = "precio" type="text" class="form-control" value="{{libro.precio}}" >
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Cantidad</label>
                                <input  name = "cantidad" id = "cantidad" type="text" class="form-control" value="{{libro.cantidad}}">
                            </div>
                            <div class="form-group">
                                <label for="url_imagen">Imagen</label>
                                {% if libro.url_imagen %}
                                    <img src="{{url_for('static',filename = libro.url_imagen)}}" width="100px" alt="">
                                {% endif %}
                                <input class= "form-control" type="file" name="url_imagen" id="url_imagen" value="">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('libro.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/libro/eliminar.html
{% extends 'layout_interno.html' %}

{% block title%} Eliminar Libro {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Eliminar Libro</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{libro.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Libro</label>
                                <input disabled name = "nombre_libro" id = "nombre_libro" type="text" class="form-control" value="{{libro.nombre_libro}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Categoria</label>
                                <input disabled name = "nombre_categoria" id = "nombre_categoria" type="text" class="form-control" value="{{libro.nombre_categoria}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Autor</label>
                                <input disabled name = "nombre_autor" id = "nombre_autor" type="text" class="form-control" value="{{libro.nombre_autor}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Nombre Editorial</label>
                                <input disabled name = "nombre_editorial" id = "nombre_editorial" type="text" class="form-control" value="{{libro.nombre_editorial}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Precio</label>
                                <input disabled name = "precio" id = "precio" type="text" class="form-control" value="{{libro.precio}}">
                            </div>
                            <div class="form-group">
                                <label for="nombre_libro">Cantidad</label>
                                <input disabled name = "cantidad" id = "cantidad" type="text" class="form-control" value="{{libro.cantidad}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('libro.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--<script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/libro/index.html
{% extends 'layout_interno.html' %}

{% block title%} Libros {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="offset-10 col-3 my-3">
                <a href="{{url_for('libro.crear')}}" class="btn btn-success">Crear Libro</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="card border border-dark shadow mb-3">
                <div class="card-header bg-primary">
                    <h1 class="h1 text-white text-center">Listado de  Libros</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="Tabla">
                            <thead class="table-primary">
                                <tr>
                                    <td>#</td>
                                    <td>Nombre</td>
                                    <td>Editorial</td>
                                    <td>Autor</td>
                                    <td>Precio</td>
                                    <td>Cantidad</td>
                                    <td>Estado</td>
                                    <td>Acciones</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for libro in libros %}
                                    <tr>
                                        <td>{{libro.id}}</td>
                                        <td>{{libro.nombre_libro}}</td>
                                        <td>{{libro.nombre_editorial}}</td>
                                        <td>{{libro.nombre_autor}}</td>
                                        <td>{{libro.precio}}</td>
                                        <td>{{libro.cantidad}}</td>
                                        {% if libro.activo %}
                                            <td>Activo</td>
                                        {% else %}
                                            <td>Inactivo</td>
                                        {% endif %}
                                        <td>
                                            <a href="{{url_for('libro.detalle', id=libro.id)}}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                                            <a href="{{url_for('libro.editar', id=libro.id)}}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                            <a href="{{url_for('libro.eliminar', id = libro.id )}}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}