controllers/editorialController.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from models.editorialModel import EditorialModel

editorialbp = Blueprint("editorial", __name__)

@editorialbp.route("/editorial/crear", methods = ['GET','POST'])
def crear():
    if request.method == 'POST':
        nombre_editorial = request.form['nombre_editorial']

        retorno = EditorialModel().crearEditorial(nombre_editorial)
        print(retorno)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('editorial.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo crear el editorial", "error"))
            return render_template("/editorial/crear.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/editorial/crear.html")

@editorialbp.route("/editorial/", methods=['GET', 'POST'])
def index():
    editoriales = EditorialModel().listarEditoriales()
    return render_template('/editorial/index.html',editoriales = editoriales)

@editorialbp.route("/editorial/editar/<int:id>", methods = ['GET','POST'])
def editar(id):
    editorial = EditorialModel().buscarEditorial(id)
    if request.method == 'POST':
        nombre_editorial = request.form['nombre_editorial']

        retorno = EditorialModel().actualizarEditorial(id, nombre_editorial)

        if retorno > 0:
            flash(("Datos guardados correctamente", "success"))
            return redirect(url_for('editorial.index'))
        else:
            # Devuelve el template con un mensaje de error opcional
            flash(("No se pudo editar el editorial", "error"))
            return render_template("/editorial/editar.html")

    # Si es GET, solo mostramos el formulario
    return render_template("/editorial/editar.html", editorial = editorial)

@editorialbp.route("/editorial/detalle/<int:id>")
def detalle(id):
    editorial = EditorialModel().buscarEditorial(id)
    return render_template('/editorial/detalle.html',editorial = editorial)

@editorialbp.route('/editorial/eliminar/<int:id>', methods=['GET','POST'])
def eliminar(id):
    editorial = EditorialModel().buscarEditorial(id)
    if request.method == 'POST':
        retorno = EditorialModel().eliminarEditorial(id)

        if retorno > 0:
            flash(("No se pudo eliminar el editorial", "error"))
            return redirect(url_for('editorial.index'))
        else:
            flash(("No se pudo eliminar el editorial", "error"))
            return render_template("/editorial/eliminar.html", editorial = editorial)
    return render_template("/editorial/eliminar.html", editorial = editorial)
    

templates/editorial/crear.html
{% extends 'layout_interno.html' %}

{% block title%} Crear Editorial {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Crear Editorial</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <div class="form-group">
                                <label for="nombre_editorial">Nombre Editorial</label>
                                <input name = "nombre_editorial" id = "nombre_editorial" type="text" class="form-control">
                            </div>
                            <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('editorial.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/editorial/detalle.html
{% extends 'layout_interno.html' %}

{% block title%} Detalle Editorial {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Detalle Editorial</h1>
                    </div>
                    <div class="card-body">
                        <ul>
                            <p><strong>ID: </strong>{{editorial.id}}</p>
                            <p><strong>Nombre: </strong>{{editorial.nombre_editorial}}</p>
                            <a href="{{url_for('editorial.index')}}" class="btn btn-success w-100 my-3">Volver</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/editorial/editar.html
{% extends 'layout_interno.html' %}

{% block title%} Editar Editorial {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Editar Editorial</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{editorial.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_editorial">Nombre Editorial</label>
                                <input name = "nombre_editorial" id = "nombre_editorial" type="text" class="form-control" value="{{editorial.nombre_editorial}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('editorial.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/editorial/eliminar.html
{% extends 'layout_interno.html' %}

{% block title%} Eliminar Editorial {% endblock %}

{% block content %}

    <div class="container">
            <div class="row justify-content-center m-5">
                <div class="col-6">
                    <div class="card border border border-dark shadow">
                    <div class="card-header bg-primary">
                        <h1 class="h1 text-white text-center">Eliminar Editorial</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" id = "formulario" onsubmit="enviarFormulario(event,'¿Está seguro que desea guardar los cambios?')">
                            <input type ="hidden" value="{{editorial.id}}" name="id" id="id">
                            <div class="form-group">
                                <label for="nombre_editorial">Nombre Editorial</label>
                                <input disabled name = "nombre_editorial" id = "nombre_editorial" type="text" class="form-control" value="{{editorial.nombre_editorial}}">
                            </div>
                             <div class="d-flex justify-content-between my-3">
                                <input type="submit" class="btn btn-success w-50 me-2" value="Guardar">
                                <a href="{{url_for('editorial.index')}}" class="btn btn-primary w-50">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}

templates/editorial/index.html
{% extends 'layout_interno.html' %}

{% block title%} Editoriales {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="offset-10 col-3 my-3">
                <a href="{{url_for('editorial.crear')}}" class="btn btn-success">Crear Editorial</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="card border border-dark shadow mb-3">
                <div class="card-header bg-primary">
                    <h1 class="h1 text-white text-center">Listado de  Editoriales</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="Tabla">
                            <thead class="table-primary">
                                <tr>
                                    <td>#</td>
                                    <td>Nombre</td>
                                    <td>Acciones</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for editorial in editoriales %}
                                    <tr>
                                        <td>{{editorial.id}}</td>
                                        <td>{{editorial.nombre_editorial}}</td>
                                        <td>
                                            <a href="{{url_for('editorial.detalle', id=editorial.id)}}" class="btn btn-info"><i class="fas fa-info-circle"></i></a>
                                            <a href="{{url_for('editorial.editar',id=editorial.id)}}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                            <a href="{{url_for('editorial.eliminar',id=editorial.id)}}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="{{url_for('static',filename='js/confirmarGuardado.js')}}"></script>

{% endblock %}